name: api

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/api.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Zappa
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

          cat > zappa_settings.json << EOL
          {
            "production": {
              "app_function": "run.app",
              "domain": "${{ secrets.DOMAIN }}",
              "route53": true,
              "certificate_arn": "${{ secrets.CERTIFICATE_ARN }}",
              "base_path": "",
              "aws_region": "${{ secrets.AWS_REGION }}",
              "manage_roles": true,
              "role_name": "${{ secrets.PROJECT_NAME }}-production-ZappaLambdaExecutionRole",
              "project_name": "${{ secrets.PROJECT_NAME }}",
              "runtime": "python3.12",
              "s3_bucket": "${{ secrets.PROJECT_NAME }}",
              "environment_variables": {
                "SECRET_KEY": "${{ secrets.SECRET_KEY }}",
                "SESSION_NAME_KEY": "${{ secrets.SESSION_NAME_KEY }}",
                "FERNET_KEY": "${{ secrets.FERNET_KEY }}",
                "CSRF_SCRIPT_NAME": "${{ secrets.CSRF_SCRIPT_NAME }}",
                "SQLALCHEMY_DATABASE_URI": "${{ secrets.SQLALCHEMY_DATABASE_URI }}",
                "CLUB_ID": "${{ secrets.CLUB_ID }}",
                "CLUB_NAME": "${{ secrets.CLUB_NAME }}",
                "COURSE_ID": "${{ secrets.COURSE_ID }}",
                "PROXY_URL": "${{ secrets.PROXY_URL }}",
                "PROXY_LOGIN": "${{ secrets.PROXY_LOGIN }}",
                "PROXY_LOGOUT": "${{ secrets.PROXY_LOGOUT }}",
                "PROXY_HOME": "${{ secrets.PROXY_HOME }}",
                "PROXY_SEARCH": "${{ secrets.PROXY_SEARCH }}",
                "PROXY_PEOPLE": "${{ secrets.PROXY_PEOPLE }}",
                "PROXY_RESERVE": "${{ secrets.PROXY_RESERVE }}",
                "PROXY_REFERER": "${{ secrets.PROXY_REFERER }}",
                "SOURCE": "${{ secrets.SOURCE }}",
                "ALLOWED_ORIGINS": "${{ secrets.ALLOWED_ORIGINS }}"
              }
            }
          }
          EOL

          zappa update production
