name: api

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/api.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up ./api --service ${{ secrets.RAILWAY_SERVICE_ID }}